# Generated by Django 3.2.16 on 2023-04-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0002_alter_membro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='imagem',
            field=models.ImageField(upload_to='membros'),
        ),
    ]
