# Generated by Django 3.2.16 on 2023-04-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0003_alter_membro_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='diretorias')),
                ('ordem', models.IntegerField()),
                ('descricao', models.TextField(max_length=511)),
            ],
        ),
    ]
