# Generated by Django 3.2.16 on 2023-04-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0004_diretoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=100)),
                ('resposta', models.TextField(max_length=511)),
                ('ordem', models.IntegerField()),
            ],
        ),
    ]
