# Generated by Django 3.2.16 on 2023-04-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0005_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('whatsapp', models.URLField(max_length=100)),
                ('ordem', models.IntegerField()),
            ],
        ),
    ]
