# Generated by Django 3.2.16 on 2023-05-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0002_auto_20230502_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='requisitos',
            field=models.TextField(blank=True),
        ),
    ]
