# Generated by Django 3.2.16 on 2023-04-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semov', '0003_auto_20230428_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('dia', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('tipo', models.CharField(choices=[('Palestra', 'Palestra'), ('Workshop', 'Workshop'), ('Processo Seletivo', 'Processo Seletivo'), ('Visita Técnica', 'Visita Técnica'), ('Resolução de Case', 'Resolução de Case'), ('Minicurso', 'Minicurso')], max_length=20)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.AlterModelOptions(
            name='patrocinador',
            options={'verbose_name': 'Patrocinador', 'verbose_name_plural': 'Patrocinadores'},
        ),
    ]
