# Generated by Django 3.2.16 on 2023-04-29 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semov', '0004_auto_20230429_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semov.data'),
        ),
    ]
