# Generated by Django 3.2.16 on 2023-04-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semov', '0005_auto_20230429_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='dia_da_semana',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
