# Generated by Django 3.2.16 on 2023-04-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semov', '0006_data_dia_da_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='descricao',
        ),
    ]
