# Generated by Django 3.2.16 on 2023-05-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semov', '0007_remove_evento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('PALESTRA', 'Palestra'), ('WORKSHOP', 'Workshop'), ('PROCESSO SELETIVO', 'Processo Seletivo'), ('VISITA TÈCNICA', 'Visita Técnica'), ('RESOLUÇÂO DE CASE', 'Resolução de Case'), ('MINICURSO', 'Minicurso')], max_length=20),
        ),
    ]
